# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\"\x17\n\x07Request\x12\x0c\n\x04info\x18\x01 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t22\n\x08Service1\x12&\n\rListenAndSend\x12\x08.Request\x1a\t.Response\"\x00\x32\x33\n\x08Service2\x12\'\n\x0e\x45xecuteRoutine\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=18
  _globals['_REQUEST']._serialized_end=41
  _globals['_RESPONSE']._serialized_start=43
  _globals['_RESPONSE']._serialized_end=69
  _globals['_SERVICE1']._serialized_start=71
  _globals['_SERVICE1']._serialized_end=121
  _globals['_SERVICE2']._serialized_start=123
  _globals['_SERVICE2']._serialized_end=174
# @@protoc_insertion_point(module_scope)
